trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']
pool:
  vmImage: windows-latest
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- powershell: |
    yarn --frozen-lockfile
  displayName: Install Dependencies

- powershell: |
    yarn test
  displayName: Test Package