stages:
- stage: Windows
  pool:
    vmImage: windows-latest
  jobs:
  - job: win_x64
    variables:
      VSCODE_ARCH: x64
    steps:
      - template: templates/windows.yml
  - job: win_ia32
    variables:
      VSCODE_ARCH: ia32
    steps:
      - template: templates/windows.yml
- stage: macOS
  pool:
    vmImage: macos-latest
  jobs:
  - job: darwin_x64
    variables:
      VSCODE_ARCH: x64
    steps:
      - template: templates/macos.yml

trigger:
  branches:
   include:
   - main
