name: run-tests
on: push
jobs:
  yarn-windows:
    name: yarn-windows
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Run yarn
      run: |
        yarn --frozen-lockfile && yarn test